Use Firestore subcollections
AP-Students/website pull request #131
Opened 2024-12-21 06:00 UTC by BrilliantDeviation7

2024-12-21 07:21 UTC, manningwu07 requested changes

2024-12-21 16:27 UTC, BrilliantDeviation7 commented on src/components/questions/testRenderer.tsx
> +                {questions.length > 0 &&
This one is outside of the one on line 142.

2024-12-21 16:42 UTC, BrilliantDeviation7 commented on src/app/admin/subject/[slug]/page.tsx
>      updatedUnits.splice(unitIndex, 1);
The `unit` property (the unit number) no longer exists for each unit object, so simply removing it from the array will work.

2024-12-26 23:31 UTC, manningwu07 commented on src/app/admin/subject/[slug]/page.tsx
> +      // TODO: update Firestore security rules
Firebase sec rules dont need to change

2025-01-18 05:35 UTC, manningwu07 approved these changes
Trust u on this one

2025-01-18 05:48 UTC, manningwu07 approved these changes

2025-01-18 05:50 UTC, merged