Subject page
AP-Students/website pull request #42
Opened 2024-07-14 07:42 UTC by EthanL06

For #38

2024-07-14 07:44 UTC, EthanL06 commented
Todo: 

- Make responsive
- Add table of contents
- Add footer

2024-07-14 23:21 UTC, alexng353 requested changes

2024-07-14 23:21 UTC, alexng353 commented on src/app/_components/subject-sidebar.tsx
> +          {props.subject.units.map((unit) => (
separate this (the inside) into it's own component

2024-07-14 23:21 UTC, alexng353 commented on src/app/_components/subject-sidebar.tsx
> +          className={cn(isCollapsed ? "animate-hide" : "")}
isCollapsed && ".." should work here

2024-07-14 23:21 UTC, alexng353 commented on src/app/_components/table-of-contents.tsx
> +            href={`/subject/ap-calc-ab#${unit.title}`}
this should not be hard coded

2024-07-14 23:21 UTC, alexng353 commented on src/app/subject/[slug]/page.tsx
> +              {subject.units.map((unit) => (
again, separate the inside of this map into its own component

2024-07-14 23:21 UTC, alexng353 commented on src/app/subject/[slug]/page.tsx
> +            </Breadcrumb>
probably make this its own component too

2024-07-14 23:21 UTC, alexng353 commented on src/lib/types.ts
types should be a folder with a barrel file that exports from files within the types folder. Because this will expand in the future and you will be sad when you need to refactor it.

2024-07-15 06:25 UTC, EthanL06 commented on src/app/_components/subject-sidebar.tsx
> +        "sticky top-0 hidden max-h-screen shrink-0 overflow-y-auto overflow-x-hidden bg-primary-foreground px-3 pb-12 pt-[11.5rem] transition-all duration-300 ease-in-out scrollbar scrollbar-track-pr
just for this div or for all the files? right now, i'm just going by how Prettier sorts it

2024-07-15 06:58 UTC, EthanL06 commented
@alexng353 made requested changes

2024-07-21 16:59 UTC, merged