Add magic link email provider
AP-Students/website pull request #58
Opened 2024-07-28 01:41 UTC by AlokSwaminathan

Needs to be discussed whether this is even a good idea since we need an email client to send these emails from.

If this is something we want to do then we need to customize the email so it fits the brand. I can do this if its decided that magic links are good. Also need to set up some sort of database check so if the email is new they get sent to a registration page.

Personally I think its worth the effort to set up a good, secure email password login system and I'm willing to do it. But this could still be a nice alternative even if email password auth is setup.

2024-07-29 06:01 UTC, alexng353 requested changes

2024-07-29 06:01 UTC, alexng353 commented on pnpm-lock.yaml
You need to upgrade your PNPM to version 9.5.0 or higher. This diff only exists because you are using a pnpm with version less than or equal to 8.5.7, which uses the old lockfile specification.

2024-07-29 06:01 UTC, alexng353 commented on pnpm-lock.yaml
This pull request will not be merged unless the lockfile conflicts are dealt with.

2024-08-31 01:35 UTC, manningwu07 commented
Email auth has been added, and there is a forget password with infinite number of attempts (gotta fix for security issues later but...) so this isn't really nessecary. We also have OAuth for google.

2024-08-31 01:35 UTC, closed without merging