Account management improvements
AP-Students/website pull request #97
Opened 2024-11-20 03:39 UTC by AlokSwaminathan

2024-11-24 02:49 UTC, BrilliantDeviation7 approved these changes
I've fixed any issues I found; rest looks good to me.

2024-11-28 05:19 UTC, manningwu07 commented
Code logic looks fine and styling stuff can be tuned later; can you make sure to fix/patch all deploy errors from this PR? I can then approve merging afterwards.

2024-11-29 07:32 UTC, manningwu07 submitted a review, later dismissed
Code logic looks fine and styling stuff can be tuned later

can you make sure to fix/patch all deploy errors from this PR? I can then approve merging afterwards.

2024-12-15 04:34 UTC, BrilliantDeviation7 requested changes

2024-12-15 04:34 UTC, BrilliantDeviation7 commented on src/lib/auth.ts
> -  const signInWithGoogle = async () => {
Bring back `signInWithGoogle` here and in `src\app\login\page.tsx`. Removing this breaks the login. We can clean it up later, but for now let's just keep this here.

2024-12-15 04:34 UTC, BrilliantDeviation7 commented on src/lib/auth.ts
> -    signInWithGoogle,
Keep this (see first comment).

2024-12-15 18:57 UTC, BrilliantDeviation7 approved these changes

2024-12-15 19:26 UTC, merged